// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MACAddress struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MACAddress) Reset()         { *m = MACAddress{} }
func (m *MACAddress) String() string { return proto.CompactTextString(m) }
func (*MACAddress) ProtoMessage()    {}
func (*MACAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{0}
}

func (m *MACAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MACAddress.Unmarshal(m, b)
}
func (m *MACAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MACAddress.Marshal(b, m, deterministic)
}
func (m *MACAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MACAddress.Merge(m, src)
}
func (m *MACAddress) XXX_Size() int {
	return xxx_messageInfo_MACAddress.Size(m)
}
func (m *MACAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MACAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MACAddress proto.InternalMessageInfo

func (m *MACAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Lease struct {
	MACAddress           string               `protobuf:"bytes,1,opt,name=MACAddress,proto3" json:"MACAddress,omitempty"`
	IPAddress            string               `protobuf:"bytes,2,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	LeaseEnd             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=LeaseEnd,proto3" json:"LeaseEnd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Lease) Reset()         { *m = Lease{} }
func (m *Lease) String() string { return proto.CompactTextString(m) }
func (*Lease) ProtoMessage()    {}
func (*Lease) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{1}
}

func (m *Lease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lease.Unmarshal(m, b)
}
func (m *Lease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lease.Marshal(b, m, deterministic)
}
func (m *Lease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lease.Merge(m, src)
}
func (m *Lease) XXX_Size() int {
	return xxx_messageInfo_Lease.Size(m)
}
func (m *Lease) XXX_DiscardUnknown() {
	xxx_messageInfo_Lease.DiscardUnknown(m)
}

var xxx_messageInfo_Lease proto.InternalMessageInfo

func (m *Lease) GetMACAddress() string {
	if m != nil {
		return m.MACAddress
	}
	return ""
}

func (m *Lease) GetIPAddress() string {
	if m != nil {
		return m.IPAddress
	}
	return ""
}

func (m *Lease) GetLeaseEnd() *timestamp.Timestamp {
	if m != nil {
		return m.LeaseEnd
	}
	return nil
}

type Leases struct {
	List                 []*Lease `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Leases) Reset()         { *m = Leases{} }
func (m *Leases) String() string { return proto.CompactTextString(m) }
func (*Leases) ProtoMessage()    {}
func (*Leases) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{2}
}

func (m *Leases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Leases.Unmarshal(m, b)
}
func (m *Leases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Leases.Marshal(b, m, deterministic)
}
func (m *Leases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Leases.Merge(m, src)
}
func (m *Leases) XXX_Size() int {
	return xxx_messageInfo_Leases.Size(m)
}
func (m *Leases) XXX_DiscardUnknown() {
	xxx_messageInfo_Leases.DiscardUnknown(m)
}

var xxx_messageInfo_Leases proto.InternalMessageInfo

func (m *Leases) GetList() []*Lease {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*MACAddress)(nil), "proto.MACAddress")
	proto.RegisterType((*Lease)(nil), "proto.Lease")
	proto.RegisterType((*Leases)(nil), "proto.Leases")
}

func init() {
	proto.RegisterFile("control.proto", fileDescriptor_0c5120591600887d)
}

var fileDescriptor_0c5120591600887d = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2b,
	0x29, 0xca, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0xf2, 0xe9,
	0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x49, 0x66, 0x6e, 0x6a,
	0x71, 0x49, 0x62, 0x6e, 0x01, 0x44, 0x9d, 0x94, 0x34, 0xba, 0x82, 0xd4, 0xdc, 0x82, 0x92, 0x4a,
	0x88, 0xa4, 0x92, 0x1a, 0x17, 0x97, 0xaf, 0xa3, 0xb3, 0x63, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0xb1,
	0x90, 0x04, 0x17, 0x3b, 0x94, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x2a, 0xd5,
	0x72, 0xb1, 0xfa, 0xa4, 0x26, 0x16, 0xa7, 0x0a, 0xc9, 0x21, 0x6b, 0x80, 0xaa, 0x42, 0x36, 0x42,
	0x86, 0x8b, 0xd3, 0x33, 0x00, 0x26, 0xcd, 0x04, 0x96, 0x46, 0x08, 0x08, 0x99, 0x71, 0x71, 0x80,
	0x8d, 0x71, 0xcd, 0x4b, 0x91, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0x38, 0x4f,
	0x0f, 0xe6, 0x3c, 0xbd, 0x10, 0x98, 0xfb, 0x83, 0xe0, 0x6a, 0x95, 0xb4, 0xb8, 0xd8, 0xc0, 0xec,
	0x62, 0x21, 0x05, 0x2e, 0x16, 0x9f, 0xcc, 0xe2, 0x12, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23,
	0x1e, 0x88, 0x36, 0x3d, 0xb0, 0x64, 0x10, 0x58, 0xc6, 0x68, 0x05, 0x23, 0x17, 0x0f, 0x98, 0xef,
	0x0c, 0x09, 0x2e, 0x21, 0x23, 0x2e, 0x8e, 0xe0, 0xd4, 0x12, 0x88, 0xf3, 0x51, 0x34, 0x48, 0x89,
	0x61, 0x58, 0xee, 0x0a, 0x0a, 0x1b, 0x25, 0x06, 0x21, 0x5d, 0x2e, 0x0e, 0x77, 0x98, 0x1e, 0x41,
	0xa8, 0x1e, 0x84, 0x2f, 0xa5, 0x50, 0x8c, 0x51, 0x62, 0x10, 0x32, 0xe5, 0xe2, 0x02, 0xd9, 0x0d,
	0x75, 0x23, 0x0e, 0x63, 0xa5, 0x78, 0x91, 0x75, 0x15, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0xf9, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0xf7, 0x29, 0x72, 0xda, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LeaseControlClient is the client API for LeaseControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeaseControlClient interface {
	SetLease(ctx context.Context, in *Lease, opts ...grpc.CallOption) (*empty.Empty, error)
	GetLease(ctx context.Context, in *MACAddress, opts ...grpc.CallOption) (*Lease, error)
	ListLeases(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Leases, error)
}

type leaseControlClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaseControlClient(cc grpc.ClientConnInterface) LeaseControlClient {
	return &leaseControlClient{cc}
}

func (c *leaseControlClient) SetLease(ctx context.Context, in *Lease, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.LeaseControl/SetLease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseControlClient) GetLease(ctx context.Context, in *MACAddress, opts ...grpc.CallOption) (*Lease, error) {
	out := new(Lease)
	err := c.cc.Invoke(ctx, "/proto.LeaseControl/GetLease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseControlClient) ListLeases(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Leases, error) {
	out := new(Leases)
	err := c.cc.Invoke(ctx, "/proto.LeaseControl/ListLeases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaseControlServer is the server API for LeaseControl service.
type LeaseControlServer interface {
	SetLease(context.Context, *Lease) (*empty.Empty, error)
	GetLease(context.Context, *MACAddress) (*Lease, error)
	ListLeases(context.Context, *empty.Empty) (*Leases, error)
}

// UnimplementedLeaseControlServer can be embedded to have forward compatible implementations.
type UnimplementedLeaseControlServer struct {
}

func (*UnimplementedLeaseControlServer) SetLease(ctx context.Context, req *Lease) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLease not implemented")
}
func (*UnimplementedLeaseControlServer) GetLease(ctx context.Context, req *MACAddress) (*Lease, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLease not implemented")
}
func (*UnimplementedLeaseControlServer) ListLeases(ctx context.Context, req *empty.Empty) (*Leases, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLeases not implemented")
}

func RegisterLeaseControlServer(s *grpc.Server, srv LeaseControlServer) {
	s.RegisterService(&_LeaseControl_serviceDesc, srv)
}

func _LeaseControl_SetLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseControlServer).SetLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LeaseControl/SetLease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseControlServer).SetLease(ctx, req.(*Lease))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseControl_GetLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MACAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseControlServer).GetLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LeaseControl/GetLease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseControlServer).GetLease(ctx, req.(*MACAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseControl_ListLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseControlServer).ListLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LeaseControl/ListLeases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseControlServer).ListLeases(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeaseControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LeaseControl",
	HandlerType: (*LeaseControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLease",
			Handler:    _LeaseControl_SetLease_Handler,
		},
		{
			MethodName: "GetLease",
			Handler:    _LeaseControl_GetLease_Handler,
		},
		{
			MethodName: "ListLeases",
			Handler:    _LeaseControl_ListLeases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control.proto",
}
